### ISSUE TITLE
Warning for when report search yields no results

### ISSUE THREAD

**Issue by seanccsmith** [CareSet/Zermelo#124]
When a query meant to populate a report yields no results, Zermelo should say so explicitly. In the Lore Commander card face browser, we thought there was a bug in Zermelo, when really it was a problem in the population of the database. This would be fixed by adding a notice that the query has been performed successfully, and returned no results. Either after performing a search, or in the initial query to build the report.

**Comment by kchapple** [comment]
This is fixed in the zermelobladecardpackage

![Screen Shot 2020-06-05 at 10 09 08 AM](https://user-images.githubusercontent.com/271809/83886515-2aa79900-a715-11ea-87e6-4d9ac1cf1585.png)

**Comment by seanccsmith** [comment]
On the real tables, I'm still getting not getting the warning (this is from Card Search Using Card Display):

![Screen Shot 2020-06-05 at 12 07 14 PM](https://user-images.githubusercontent.com/42678849/83904288-38fdb100-a725-11ea-85a2-289ab2a8b335.png)

There is a nice "no data" warning for the Simple Card Search, but not in these higher-level reports.

**Comment by kchapple** [comment]
@seanccsmith make sure you have the latest card view template, and then run install to install (the installer will probably tell you that the card view is different and ask you if you want to overwrite it, say "yes")

php artisan zermelo:install

**Comment by seanccsmith** [comment]
That did it. This is working now.
